Algoritmo "média"

Var
n1:real
n2:real
media:real

Inicio
escreval("DIgite o valor de N1 ")
leia(n1)
escreval("Digite o valor de N2")
leia(n2)
media <- (n1 + n2 )/2

      se media>7 entao
      escreval("Aprovado com media ",media)
      senao
      
      se media<5 entao
      escreval("Reprovado com media ",media)
      senao
      escreval("Recuperação com média ",media)
           fimse
      fimse

        















Fimalgoritmo