Algoritmo "Troca de Valores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2023
Var
A:inteiro
B:inteiro
C:inteiro



Inicio
A <- 10
B <- 20
C <- 0

C <- A
B <- C
A <- B
ESCREVAL (A)
ESCREVAL (B)
ESCREVAL (C)

Fimalgoritmo