Algoritmo "TROCA DE VALORES 3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2023
Var
// Seção de Declarações das variáveis 
X:inteiro
Y:inteiro
Z:inteiro

Inicio
X <- 1
Y <- 2
Z <- 0
Z <- Y-X
ESCREVAL (Z)
X <- 5
Y <- X+Z
ESCREVAL (X,Y,Z)



Fimalgoritmo