Algoritmo "Troca de Algritmos 2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2023
Var
A:inteiro
B:inteiro
C:inteiro


Inicio
A <-30
B <-20
C <-0
C <- (A+B)
ESCREVAL (C)
B <- 10
ESCREVAL (B,C)
C <- (A+B)
ESCREVAL (A,B,C)


Fimalgoritmo