Algoritmo "calcularidade"
// MOD UM VELHO SABIO DISSE:ARARARARARAA ERHGFYRFYSUYGI ELE ERA MUDO
Var
// Seção de Declarações das variáveis
nome: caracter
anoNasc: inteiro
idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Digite seu nome completo:")
leia(nome)
escreval("Digite seu ano de nascimento:")
leia(anoNasc)

idade <- 2023 - anoNasc

escreval("A sua idade é: ",idade,"anos de idade")



Fimalgoritmo