Algoritmo "escolha"


Var
time:caracter

Inicio
escreval("Digite o nome de um TIME")
leia(time)

 escolha time
 
  caso "São Paulo","Palmeiras","Corinthians"
     escreval("VOCÊ ESCOLHEU UM TIME PAULISTA")
   
   caso "Flamengo","Vasco","Botafogo"
     escreval("VOCÊ ESCOLHEU UM TIME CARIOCA")
   
   caso "Grêmio","Cruzeiro","Inter"
     escreval("VOCÊ ESCOLHEU UM TIME SULISTA")
   
   Outrocaso
     escreval("TIME Invalido")

fimescolha




Fimalgoritmo