algoritmo "semnome"

var
numero:inteiro


inicio

escreval("DIgite um número qualquer")
leia(numero)

se numero>0 entao
   numero <- numero*2
   escreval("O seu numero positivo sera deplicado por 2 resultando em", numero)
senao
se numero<0 entao
   numero <- numero*3
   escreval escreval("O seu numero positivo sera deplicado por 3 resultando em", numero)
   senao
   escreval("o seu número é invalído")
   
   fimse
fimse





fimalgoritmo
